#!/bin/sh /etc/rc.common

START=99

apply_all() {
	local iface
	for iface in $(uci -q show basic-mesh | sed -n 's/^basic-mesh\.\([^.]*\)=mesh_params$/\1/p'); do
		basic-mesh-apply "$iface"
	done
}

start() {
	apply_all
}

restart() {
	apply_all
}

reload() {
	apply_all
}
